import pandas as pd
import os
from config import PATH
df = pd.read_csv(PATH + 'mountain_rebel/cheese_set.csv')
#set random cheese
#create folder in projects, name it cheese_name
#create file README.md in cheese_name folder
#define README.md template
random_cheese = df.sample(replace=False)
#print(random_cheese)

#create folder
vars = {
    "cheese_name": random_cheese.iat[0,0],
    "cheese_milk": random_cheese.iat[0,1],
    "cheese_type": random_cheese.iat[0,2],
    "cheese_texture": random_cheese.iat[0,3],
    "cheese_url": random_cheese.iat[0,4],
}

template = """\
# {cheese_name}
## *Milk: {cheese_milk}; Type: {cheese_type}; Texture: {cheese_texture}*
### More info available [here]({cheese_url})
### This .md header generated by Cheesely, an fbaum project.
"""
readme = template.format(**vars)

print(str(vars["cheese_name"]))
cheese_path = os.path.join(PATH, str(vars["cheese_name"]))
try:
    os.makedirs(cheese_path, exist_ok=True)
    print(f"Folder '{str(vars["cheese_name"])}' created")
except OSError as e:
    print(f"Error: {e}")

#create README.md in folder
readme_path = os.path.join(cheese_path, "README.md")
with open(readme_path, "w") as file:
    file.write(readme)
print("README successful")
#take random cheese out of rotation to prevent dupes
df.to_csv('cheese_set.csv', index=False)

